// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmFvAM_2_9MpgBqPd0kwT_bXhhtBcKDGw',
    appId: '1:525041660426:web:c511067e065a83ad8265f3',
    messagingSenderId: '525041660426',
    projectId: 'postapp-2af55',
    authDomain: 'postapp-2af55.firebaseapp.com',
    storageBucket: 'postapp-2af55.appspot.com',
    measurementId: 'G-T0C8HLBFPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDveBxtUm1EG-2a3sJgRMagBJQZTvGrrOc',
    appId: '1:525041660426:android:ce955d3f78e3a1f98265f3',
    messagingSenderId: '525041660426',
    projectId: 'postapp-2af55',
    storageBucket: 'postapp-2af55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbhMCMxjIMOQsGdA25LU9qaw8d4PelL4',
    appId: '1:525041660426:ios:ce91666c5bbb571a8265f3',
    messagingSenderId: '525041660426',
    projectId: 'postapp-2af55',
    storageBucket: 'postapp-2af55.appspot.com',
    iosClientId: '525041660426-kfoibb1rpe24buvjjp71kog0b5ksiqdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterPostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZbhMCMxjIMOQsGdA25LU9qaw8d4PelL4',
    appId: '1:525041660426:ios:ce91666c5bbb571a8265f3',
    messagingSenderId: '525041660426',
    projectId: 'postapp-2af55',
    storageBucket: 'postapp-2af55.appspot.com',
    iosClientId: '525041660426-kfoibb1rpe24buvjjp71kog0b5ksiqdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterPostApp',
  );
}
